// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRf_fFVowjcpD9pCmUvVBV8ja3fr-XbLs',
    appId: '1:1058148863122:web:f7a0ca6d03db6d3e68aa4b',
    messagingSenderId: '1058148863122',
    projectId: 'hackathon-2c3d7',
    authDomain: 'hackathon-2c3d7.firebaseapp.com',
    storageBucket: 'hackathon-2c3d7.firebasestorage.app',
    measurementId: 'G-0NN6JETS8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTI46B5ScMrPW-P20-1ltYeXKqK9NeskI',
    appId: '1:1058148863122:android:e510790fc1c8323b68aa4b',
    messagingSenderId: '1058148863122',
    projectId: 'hackathon-2c3d7',
    storageBucket: 'hackathon-2c3d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20JVr6vyKXYzdPE3F1FpXOx49A309QU8',
    appId: '1:1058148863122:ios:ef851bff09d45d6d68aa4b',
    messagingSenderId: '1058148863122',
    projectId: 'hackathon-2c3d7',
    storageBucket: 'hackathon-2c3d7.firebasestorage.app',
    iosBundleId: 'com.ecoeatsgroceryapp.ecoeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC20JVr6vyKXYzdPE3F1FpXOx49A309QU8',
    appId: '1:1058148863122:ios:ef851bff09d45d6d68aa4b',
    messagingSenderId: '1058148863122',
    projectId: 'hackathon-2c3d7',
    storageBucket: 'hackathon-2c3d7.firebasestorage.app',
    iosBundleId: 'com.ecoeatsgroceryapp.ecoeats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRf_fFVowjcpD9pCmUvVBV8ja3fr-XbLs',
    appId: '1:1058148863122:web:71b502aae4208e5d68aa4b',
    messagingSenderId: '1058148863122',
    projectId: 'hackathon-2c3d7',
    authDomain: 'hackathon-2c3d7.firebaseapp.com',
    storageBucket: 'hackathon-2c3d7.firebasestorage.app',
    measurementId: 'G-DNKJCWJXKF',
  );

}